In [1]:
from distribution_generator.distributions import get_rv

mutinfo = 0.3

rv = get_rv(mutinfo,2,2,n_generations=300, min_val=1e-2)
print(rv.joint_dist)
rv2 = get_rv(mutinfo,2,2,n_generations=300, min_val=1e-2)
print(rv2.joint_dist)

Best fitness: -3.651473764398894e-05: 100%|██████████| 300/300 [00:03<00:00, 98.77it/s]  

[[0.15018451 0.48907359]
 [0.35103317 0.00970874]]
[[0.15018451 0.48907359]
 [0.35103317 0.00970874]]


In [2]:
samples = rv.rvs(size=1000)
print(samples[:10])

[[1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 0]]


In [3]:
import numpy as np

dist = np.array([[4.18143636e-01, 2.35034442e-05],
 [2.90373778e-01, 2.91459083e-01]])

# compute kl with uniform distribution

kl = np.sum(dist * np.log(dist / np.array([[0.25,0.25],[0.25,0.25]])))
print(kl)

# compute mutinfo
px = np.sum(dist, axis=1)
py = np.sum(dist, axis=0)
mutinfo = 0
for i in range(2):
    for j in range(2):
        mutinfo += dist[i,j] * np.log(dist[i,j] / (px[i] * py[j]))
print(mutinfo)

# compute entropy
dist = dist.flatten()
entropy = -np.sum(dist * np.log(dist))
print(entropy)

0.3030525444939357
0.19992552028930294
1.0832418172417468
