In [1]:
from distribution_generator.distributions import get_rv
# Import binomial rv
from scipy.stats import binom

import numpy as np


def xy_map(x):
    return [x,-x,3*x]

In [6]:
mutinfo = 1.0

n = 2

noise_rv_x = binom(30,0.5)
noise_rv_y = binom(30,0.5)

rv = get_rv(mutinfo,2,2,n,n, n_generations=300, min_val=1e-2, noise_rv_x=noise_rv_x, noise_rv_y=noise_rv_y, xy_map=xy_map)
# print(rv.joint_dist)
rv2 = get_rv(mutinfo,2,2,n,n, n_generations=300, min_val=1e-2, noise_rv_x=noise_rv_x, noise_rv_y=noise_rv_y, xy_map=xy_map)
x,y = rv2.rvs(size=10000)
print(rv2.distributions)
print(rv2.mutual_information)

Best fitness: -0.0009591670770459082: 100%|██████████| 300/300 [00:02<00:00, 108.63it/s] 


[array([[0.00970874, 0.5175367 ],
       [0.43234362, 0.04041094]]), array([[0.70631098, 0.01018042],
       [0.00970874, 0.27379986]])]
1.0009515788105658


In [3]:
import numpy as np

print(np.max(x))
print(x[:5])
print(x.shape)
print(y.shape)

825
[[  64  -64  192   76  -76  228]
 [  76  -76  228   54  -54  162]
 [ 119 -119  357   76  -76  228]
 [  43  -43  129  103 -103  309]
 [  89  -89  267  104 -104  312]]
(10000, 6)
(10000, 6)


In [4]:
print(x.shape)

(10000, 6)


In [5]:
import numpy as np
from matplotlib import pyplot as plt

# Count Occurrences of Each Sample

samples = np.concatenate([x,y],axis=1)

grid = np.array([[0,0],[0,0]])
tot = 0

for sample in samples:
    grid[sample[0],sample[1]] += 1
    tot += 1

print(grid)

plt.imshow(grid, cmap='hot', interpolation='nearest', origin='lower')

IndexError: index 64 is out of bounds for axis 0 with size 2

In [19]:
import numpy as np

dist = np.array([[0.37513464, 0.24989916],
 [0.00970874, 0.36525746]])

# compute kl with uniform distribution

kl = np.sum(dist * np.log(dist / np.array([[0.25,0.25],[0.25,0.25]])))
print(kl)

# compute mutinfo
px = np.sum(dist, axis=1)
py = np.sum(dist, axis=0)
mutinfo = 0
for i in range(2):
    for j in range(2):
        mutinfo += dist[i,j] * np.log(dist[i,j] / (px[i] * py[j]))
print(mutinfo)

# compute entropy
dist = dist.flatten()
entropy = -np.sum(dist * np.log(dist))
print(entropy)

0.2590839288684114
0.20072102883245946
1.127210432251479


In [20]:
from scipy.stats import binom
import numpy as np

# Parameters for the binomial distribution
n = 10  # number of trials
p = 0.25  # probability of success

# Create a binomial distribution
binom_dist = binom(n, p)

# Calculate the probabilities of each possible outcome
probabilities = binom_dist.pmf(np.arange(n + 1))

# Calculate the entropy
entropy_binom = -np.sum(probabilities * np.log(probabilities))
print(entropy_binom)

1.7144210650734781
