In [1]:
from distribution_generator.distributions import get_rv
# Import binomial rv
from scipy.stats import binom

import numpy as np


def xy_map(x):
    return [x,-x,3*x]

In [2]:
mutinfo = 50.0

n = 100

noise_rv_x = binom(30,0.5)
noise_rv_y = binom(30,0.5)

rv = get_rv(mutinfo,2,2,n,n, n_generations=300, min_val=1e-2, noise_rv_x=noise_rv_x, noise_rv_y=noise_rv_y, xy_map=xy_map)
# print(rv.joint_dist)
rv2 = get_rv(mutinfo,2,2,n,n, n_generations=300, min_val=1e-2, noise_rv_x=noise_rv_x, noise_rv_y=noise_rv_y, xy_map=xy_map)
x,y = rv2.rvs(size=10000)
print(rv2.entropy)
print(rv2.mutual_information)

Best fitness: -0.0009088218452603103: 100%|██████████| 300/300 [00:01<00:00, 174.56it/s] 


82.58068758681105
49.97613777860871


In [3]:
import numpy as np

print(np.max(x))
print(x[:5])
print(x.shape)
print(y.shape)

1047
[[  90  -90  270 ...  135 -135  405]
 [  54  -54  162 ...   65  -65  195]
 [ 135 -135  405 ...  152 -152  456]
 [  76  -76  228 ...   89  -89  267]
 [  54  -54  162 ...   53  -53  159]]
(10000, 300)
(10000, 300)


In [ ]:
from sklearn.feature_selection import mutual_info_regression, mutual_info_classif
import numpy as np

# Example data
X = np.random.rand(100, 5)
y = np.random.rand(100)

# Using the KSG estimator for regression
mi_reg = mutual_info_regression(X, y)

# Using the KSG estimator for classification
y_class = np.random.randint(0, 2, 100)
mi_class = mutual_info_classif(X, y_class)

print("Mutual Information (Regression):", mi_reg)
print("Mutual Information (Classification):", mi_class)

In [4]:
print(x.shape)

(10000, 300)


In [5]:
import numpy as np
from matplotlib import pyplot as plt

# Count Occurrences of Each Sample

samples = np.concatenate([x,y],axis=1)

grid = np.array([[0,0],[0,0]])
tot = 0

for sample in samples:
    grid[sample[0],sample[1]] += 1
    tot += 1

print(grid)

plt.imshow(grid, cmap='hot', interpolation='nearest', origin='lower')

IndexError: index 90 is out of bounds for axis 0 with size 2

In [19]:
import numpy as np

dist = np.array([[0.37513464, 0.24989916],
 [0.00970874, 0.36525746]])

# compute kl with uniform distribution

kl = np.sum(dist * np.log(dist / np.array([[0.25,0.25],[0.25,0.25]])))
print(kl)

# compute mutinfo
px = np.sum(dist, axis=1)
py = np.sum(dist, axis=0)
mutinfo = 0
for i in range(2):
    for j in range(2):
        mutinfo += dist[i,j] * np.log(dist[i,j] / (px[i] * py[j]))
print(mutinfo)

# compute entropy
dist = dist.flatten()
entropy = -np.sum(dist * np.log(dist))
print(entropy)

0.2590839288684114
0.20072102883245946
1.127210432251479


In [20]:
from scipy.stats import binom
import numpy as np

# Parameters for the binomial distribution
n = 10  # number of trials
p = 0.25  # probability of success

# Create a binomial distribution
binom_dist = binom(n, p)

# Calculate the probabilities of each possible outcome
probabilities = binom_dist.pmf(np.arange(n + 1))

# Calculate the entropy
entropy_binom = -np.sum(probabilities * np.log(probabilities))
print(entropy_binom)

1.7144210650734781
